In [44]:
# En primer lugar importamos la libreria nltk para importar el mensaje que vamos a tratar
import nltk 
mensaje = """
* Esta es una línea de comentario y no sirve para nada 
* La estructura de la información relevante es: 
* primeros 5 digitos : id del cliente
* los siguientes 3 digitos: id del canal 
* los siguientes 5 digitos: id del evento
* Una cantidad variable de caracteres inútiles 
* El caracter "-" marca el inicio y final del precio de venta. 
* Necesitamos una tabla que estructure la información descrita anteriormente 
Patricio Fernadez, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-ergfgfggfhgfhgfh
Borja Mon de York, 0123500111111jklfgfglkjhjkhjkhjkhjkh-25.6-rtytry
Patricio Fernandez, 0123400111111jkljassaslkjhjkhjkhjkhjkh-55.3-tyt
Bruce Wayne, 0123400111111jkljlkjhjkhjkhjkhjkh-75.6-asfdsf
Micheal Jordan, 0123600111111jkljlkjhjkhjkhjkhjkh-125.6-fdgdghrtt
Patricio Fernandez, 0123600211111jkljlkjhjkhjkhjkhjkh-28.6-ererggfdv

Elidolo DelEcuador, 0123400111111jkljlkjhjkhjkrrrhjkhjkh-25.6-dsgfdgrd
* Esto es una trampa!
Peter Parker, 0123900511111jkljlkjhjkhjkhjkhjkh-75.2-fgbfb
Ignacio Gonzalez, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-dgergetg

Clark Kent, 0122200111111jkljlkgfghfhjhjkhjkhjkhjkh-15.8-sdfgfdgdg
Bruce Wayne, 0123900111111jkljlkrrrrjhjkhjkhjkhjkh-35.2-gregregr
Pepe Fulano, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-wrgrgreg"""

nltk.tokenize.line_tokenize(mensaje)

['* Esta es una línea de comentario y no sirve para nada ',
 '* La estructura de la información relevante es: ',
 '* primeros 5 digitos : id del cliente',
 '* los siguientes 3 digitos: id del canal ',
 '* los siguientes 5 digitos: id del evento',
 '* Una cantidad variable de caracteres inútiles ',
 '* El caracter "-" marca el inicio y final del precio de venta. ',
 '* Necesitamos una tabla que estructure la información descrita anteriormente ',
 'Patricio Fernadez, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-ergfgfggfhgfhgfh',
 'Borja Mon de York, 0123500111111jklfgfglkjhjkhjkhjkhjkh-25.6-rtytry',
 'Patricio Fernandez, 0123400111111jkljassaslkjhjkhjkhjkhjkh-55.3-tyt',
 'Bruce Wayne, 0123400111111jkljlkjhjkhjkhjkhjkh-75.6-asfdsf',
 'Micheal Jordan, 0123600111111jkljlkjhjkhjkhjkhjkh-125.6-fdgdghrtt',
 'Patricio Fernandez, 0123600211111jkljlkjhjkhjkhjkhjkh-28.6-ererggfdv',
 'Elidolo DelEcuador, 0123400111111jkljlkjhjkhjkrrrhjkhjkh-25.6-dsgfdgrd',
 '* Esto es una trampa!',
 'Peter Parker, 0123900511111jkljlkjhjkhjkhjkhjkh-75.2-fgbfb',
 'Ignacio Gonzalez, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-dgergetg',
 'Clark Kent, 0122200111111jkljlkgfghfhjhjkhjkhjkhjkh-15.8-sdfgfdgdg',
 'Bruce Wayne, 0123900111111jkljlkrrrrjhjkhjkhjkhjkh-35.2-gregregr',
 'Pepe Fulano, 0123400111111jkljlkjhjkhjkhjkhjkh-25.6-wrgrgreg']

In [45]:
mensaje = mensaje.splitlines()
mensaje[5]

'* los siguientes 5 digitos: id del evento'

In [57]:
import pandas as pd

def Limpieza_Datos(mensaje):
    texto =[]
    for Fila in mensaje :
        if Fila.startswith('*') == False and Fila !="":
            Elemento=Fila.split(",")
            Nombre_Cliente=Elemento[0]
            Id_Cliente=Elemento[1][0:6]
            Canal=Elemento[1][6:9]
            Evento=Elemento[1][9:14]
            Precio_Venta =Elemento[1].split("-")[1]
            texto.append([Nombre_Cliente,Id_Cliente,Canal,Evento,Precio_Venta])
    texto

    
    df = pd.DataFrame(texto, columns=['Nombre_Cliente','Id_Cliente','Canal','Evento','Precio_Venta'])
    df.loc[df["Id_Cliente"] == " 01234","Nombre_Cliente"] = "Patricio Fernandez"
    df.loc[df["Id_Cliente"] == " 01236","Nombre_Cliente"] = "Micheal Jordan"


    return df
    print (df)

In [58]:


Limpieza_Datos(mensaje)

        Nombre_Cliente Id_Cliente Canal Evento Precio_Venta
0   Patricio Fernandez      01234   001  11111         25.6
1    Borja Mon de York      01235   001  11111         25.6
2   Patricio Fernandez      01234   001  11111         55.3
3   Patricio Fernandez      01234   001  11111         75.6
4       Micheal Jordan      01236   001  11111        125.6
5       Micheal Jordan      01236   002  11111         28.6
6   Patricio Fernandez      01234   001  11111         25.6
7         Peter Parker      01239   005  11111         75.2
8   Patricio Fernandez      01234   001  11111         25.6
9           Clark Kent      01222   001  11111         15.8
10         Bruce Wayne      01239   001  11111         35.2
11  Patricio Fernandez      01234   001  11111         25.6